version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $us-east-1)
      - REPOSITORY_URI=905418038763.dkr.ecr.us-east-1.amazonaws.com/mydockerrep
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t my-volmed .
      - docker tag my-vomed:latest $905418038763.dkr.ecr.us-east-1.amazonaws.com/mydockerrep
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $905418038763.dkr.ecr.us-east-1.amazonaws.com/mydockerr
      - echo Build completed on `date`
